version: "3.8"

x-clickhouse: &ch
  image: clickhouse/clickhouse-server
  container_name: clickhouse
  ports:
    - "18123:8123"  # HTTP port
    - "19000:9000"  # TCP port
  ulimits:
    nofile:
      soft: 262144
      hard: 262144
  cap_add:
    - SYS_NICE
    - NET_ADMIN
    - IPC_LOCK
  entrypoint: "/scratch.sh"
  environment: &env
    # start server from root (useful in case of enabled user namespace)
    #      CLICKHOUSE_UID: 0
    #      CLICKHOUSE_GID: 0

    # create default database and user on starting
    CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    CLICKHOUSE_DB: scratchdb
    CLICKHOUSE_USER: scratch
    CLICKHOUSE_PASSWORD: scratch

    # custom env
    CLUSTER: local_cluster
    SECRET: scratch
  volumes: &vol
    - "./docker/clickhouse/scratch.sh:/scratch.sh"
    - "./docker/clickhouse/server/config.d:/templates"
#    - "./clickhouse/logs:/var/log/clickhouse-server"

services:
  ch_one:
    <<: *ch
    container_name: ch_one
    hostname: ch_one
    environment:
      <<: *env
      SERVER_ID: 1
      REPLICA_ID: ch_one
    volumes:
      - "./docker/clickhouse/scratch.sh:/scratch.sh"
      - "./docker/clickhouse/server/config.d:/templates"
      - "ch_one:/var/lib/clickhouse"
  ch_two:
    <<: *ch
    container_name: ch_two
    hostname: ch_two
    environment:
      <<: *env
      SERVER_ID: 2
      REPLICA_ID: ch_two
    ports:
      - "28123:8123"
      - "29000:9000"
    volumes:
      - "./docker/clickhouse/scratch.sh:/scratch.sh"
      - "./docker/clickhouse/server/config.d:/templates"
      - "ch_two:/var/lib/clickhouse"

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      DEBUG: ${DEBUG-1}
      DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - "localstack:/var/lib/localstack"
      - "./docker/localstack/resources.sh:/etc/localstack/init/ready.d/resources.sh"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  localstack:
  ch_one:
  ch_two:

