version: "3.8"

services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    ports:
      - "18123:8123"
      - "19000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
    environment:
      # start server from root (useful in case of enabled user namespace)
#      CLICKHOUSE_UID: 0
#      CLICKHOUSE_GID: 0

      # create default database and user on starting
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_DB: scratch
      CLICKHOUSE_USER: scratch
      CLICKHOUSE_PASSWORD: scratch
    volumes:
      - "clickhouse:/var/lib/clickhouse"
#      - "./clickhouse/logs:/var/log/clickhouse-server"

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      DEBUG: ${DEBUG-1}
      DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - "localstack:/var/lib/localstack"
      - "./docker/localstack/resources.sh:/etc/localstack/init/ready.d/resources.sh"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  localstack:
  clickhouse: